name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: cd /home/ubuntu/shabbas-manager && ./cd_script.sh > cd_log.log
    - name: Upload artifact for job build
      uses: actions/upload-artifact@v3
      with:
        name: cd_log
        path: /home/ubuntu/shabbas-manager/cd_log.log

