name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Deploy to Staging
      uses: Techie-Pi/node-vps-deployment@main
      with:
        remote-path: "~/shabbas-manager"
        host: ${{ secrets.HOST }}
        username: "ubuntu"
        port: 22
        password: ${{ secrets.PASSWORD }}
        pm2-id: "shabbas"
